# Generated by Django 4.0.5 on 2022-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='isbn', max_length=255),
            preserve_default=False,
        ),
    ]
