# Generated by Django 4.0.5 on 2022-06-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isbn',
        ),
    ]
