# Generated by Django 4.0.5 on 2022-06-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ISBN',
        ),
    ]
